name: CI

on:
  pull_request:
    branches: [master, next]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint

      - name: Run linter
        run: yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
